"""YouTube source adapter.

Pulls caption tracks from a YouTube video URL via ``yt-dlp`` and
converts them to plain text using :mod:`_vtt_to_text`.

Subtitle language fallback (in priority order, configurable):

    manual ``ru`` -> auto ``ru-orig`` -> auto ``ru`` -> auto ``en``

If the only available track was an auto-translated English one, the
returned stat record carries a ``quality_flag`` of
``"english_auto_translation"`` so the SKILL.md flow can warn the user.
A ``quality_flag`` of ``"encoding_recovered"`` is set when the VTT
itself was not valid UTF-8 and a codec fallback was needed.

With ``with_description=True`` the adapter also runs yt-dlp once more
with ``--write-info-json --skip-download`` to fetch metadata (title,
uploader, upload date, duration, description) and writes a
``<out>.description.md`` sidecar — see :mod:`_description`.

This module is import-safe (no network calls at import time). The
``yt-dlp`` import is deferred until :func:`fetch_youtube_transcript`
runs, so unit tests for the VTT converter do not require yt-dlp to be
installed.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable, Optional

from ._description import description_path_for, write_description_md
from ._stat import (
    SourceRateLimitError,  # re-exported for callers # noqa: F401
    TranscriptFetchError,
    TranscriptStat,
    write_stat_sidecar,
)
from ._vtt_to_text import count_speaker_turns, vtt_file_to_plain_meta


# Default fallback ladder. Each item is (kind, lang) where kind is
# "manual" (user-uploaded) or "auto" (auto-generated by YouTube).
DEFAULT_FALLBACK_RU = (
    ("manual", "ru"),
    ("auto", "ru-orig"),
    ("auto", "ru"),
    ("auto", "en"),
)

DEFAULT_TIMEOUT_SEC = 180

# yt-dlp stderr fragments that mark hard failures we should not retry.
_HARD_FAILURE_PATTERNS = (
    "video unavailable",
    "private video",
    "members-only",
    "video is age-restricted",
    "this video is only available",
)
# yt-dlp stderr fragments that mark transient / rate-limit failures.
_RATE_LIMIT_PATTERNS = (
    "http error 429",
    "too many requests",
    "sign in to confirm you're not a bot",
    "sign in to confirm your age",
)


# --------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------- #


def extract_video_id(url: str) -> Optional[str]:
    """Best-effort extraction of the 11-char YouTube video id from a URL.

    Recognises the common forms: ``youtu.be/<id>``,
    ``youtube.com/watch?v=<id>``, ``youtube.com/shorts/<id>``,
    ``youtube.com/embed/<id>``. Returns ``None`` if no id can be
    extracted (in which case yt-dlp is still capable of resolving the
    URL — the id is for stat reporting only).
    """
    patterns = (
        r"youtu\.be/([A-Za-z0-9_-]{11})",
        r"[?&]v=([A-Za-z0-9_-]{11})",
        r"youtube\.com/shorts/([A-Za-z0-9_-]{11})",
        r"youtube\.com/embed/([A-Za-z0-9_-]{11})",
    )
    for pat in patterns:
        m = re.search(pat, url)
        if m:
            return m.group(1)
    return None


def fetch_youtube_transcript(
    url: str,
    out_path: Path,
    *,
    fallback_ladder: Iterable[tuple[str, str]] = DEFAULT_FALLBACK_RU,
    yt_dlp_bin: Optional[str] = None,
    workdir: Optional[Path] = None,
    timeout_sec: int = DEFAULT_TIMEOUT_SEC,
    cookies_file: Optional[Path] = None,
    with_description: bool = False,
    description_only: bool = False,
) -> TranscriptStat:
    """Fetch a YouTube transcript, write plain text, return a stat record.

    Args:
        url: A YouTube video URL.
        out_path: Where to write the cleaned plain text.
        fallback_ladder: Iterable of ``(kind, lang)`` tuples tried in
            order. ``kind`` is ``"manual"`` (user-uploaded captions) or
            ``"auto"`` (auto-generated). The first track that yt-dlp can
            download wins. The iterable is materialised once on entry,
            so passing a generator is safe.
        yt_dlp_bin: Path to a ``yt-dlp`` executable. If ``None``, the
            tool is invoked as a Python module via the current
            interpreter (so the per-skill venv's ``yt-dlp`` is used
            without needing it on ``$PATH``).
        workdir: Optional working directory for VTT downloads. If
            ``None``, a system tempdir is used and cleaned up. Pre-existing
            VTT files in a user-supplied workdir are ignored — only
            files created during this call are considered.
        timeout_sec: Per-attempt timeout for each yt-dlp subprocess
            call. Default 180s. Increase for very long videos or flaky
            networks.
        cookies_file: Optional Netscape cookies.txt to pass to yt-dlp
            via ``--cookies``. Required for age-gated or unlisted videos.
        with_description: If True, fetch metadata via ``--write-info-json``
            and write a ``<out>.description.md`` sidecar. Populates
            ``stat.title``, ``stat.uploader``, ``stat.upload_date``,
            ``stat.duration_sec``, ``stat.description_path``.
        description_only: Skip the transcript download entirely; only
            fetch metadata and write the description sidecar. The
            returned stat's ``output_path`` still points at ``out_path``
            (the plain-text file is NOT created), and
            ``char_count``/``speaker_turn_count`` are ``0``.
            ``with_description`` is implied. Requires the caller already
            validated ``with_description`` at the CLI layer.

    Returns:
        A :class:`TranscriptStat` describing what was fetched.

    Raises:
        TranscriptFetchError: If no track in the fallback ladder could be
            downloaded (raised only when ``description_only=False``).
    """
    out_path = Path(out_path)
    video_id = extract_video_id(url)
    # Materialise once so the error path can re-iterate without exhaustion.
    ladder: tuple[tuple[str, str], ...] = tuple(fallback_ladder)
    if description_only:
        with_description = True

    cleanup_workdir = False
    if workdir is None:
        workdir = Path(tempfile.mkdtemp(prefix="transcript-fetcher-"))
        cleanup_workdir = True
    else:
        workdir = Path(workdir)
        workdir.mkdir(parents=True, exist_ok=True)

    # Snapshot of pre-existing VTT files so we never return a stale one.
    pre_existing = {p.resolve() for p in workdir.glob("*.vtt")}
    # Snapshot pre-existing info.json files — yt-dlp writes one per
    # subtitle call when ``--write-info-json`` is set, and we reuse it
    # (saving an extra subprocess round-trip) when ``with_description``
    # is requested.
    pre_existing_info = {p.resolve() for p in workdir.glob("*.info.json")}

    try:
        chosen_kind: Optional[str] = None
        chosen_lang: Optional[str] = None
        vtt_path: Optional[Path] = None
        notes: list[str] = []
        plain = ""
        codec_used = "utf-8"

        if not description_only:
            for kind, lang in ladder:
                ok, vtt_path, msg = _try_download_subtitle(
                    url=url,
                    lang=lang,
                    kind=kind,
                    workdir=workdir,
                    pre_existing=pre_existing,
                    yt_dlp_bin=yt_dlp_bin,
                    timeout_sec=timeout_sec,
                    cookies_file=cookies_file,
                    with_info_json=with_description,
                )
                if msg:
                    notes.append(msg)
                if ok and vtt_path is not None:
                    chosen_kind = kind
                    chosen_lang = lang
                    break

            if vtt_path is None or chosen_lang is None:
                tried = [f"{k}:{l}" for k, l in ladder]
                raise TranscriptFetchError(
                    f"No caption track available for {url}: tried {tried}. "
                    f"Notes: {notes[-3:] if notes else '[]'}"
                )

            plain, codec_used = vtt_file_to_plain_meta(vtt_path)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(plain, encoding="utf-8")

        quality_flag: Optional[str] = None
        if not description_only:
            if chosen_kind == "auto" and chosen_lang == "en":
                quality_flag = "english_auto_translation"
            elif codec_used not in ("utf-8", "utf-8-sig"):
                quality_flag = "encoding_recovered"
                notes.append(f"VTT was decoded as {codec_used}, not utf-8")

        stat = TranscriptStat(
            source="youtube",
            url=url,
            video_id=video_id,
            output_path=str(out_path),
            chosen_track_kind=chosen_kind,
            chosen_track_lang=chosen_lang,
            char_count=len(plain),
            speaker_turn_count=count_speaker_turns(plain) if plain else 0,
            quality_flag=quality_flag,
            notes=notes,
        )

        if with_description:
            # Prefer the info.json that piggy-backed onto a successful
            # subtitle download (saves a second yt-dlp call). Only when
            # the ladder never produced one (e.g. description_only, or
            # all ladder steps failed) do we run a dedicated fetch.
            info: Optional[dict] = _pick_fresh_info_json(workdir, pre_existing_info)
            if info is None:
                info = _fetch_video_info(
                    url=url,
                    workdir=workdir,
                    yt_dlp_bin=yt_dlp_bin,
                    timeout_sec=timeout_sec,
                    cookies_file=cookies_file,
                )
            if info is not None:
                stat.title = info.get("title")
                stat.uploader = info.get("uploader") or info.get("channel")
                stat.upload_date = _format_upload_date(info.get("upload_date"))
                stat.duration_sec = _coerce_int(info.get("duration"))
                desc_path = _write_youtube_description(
                    info=info, url=url, out_path=out_path
                )
                stat.description_path = str(desc_path)
                stat.notes.append("description: wrote .description.md")
            else:
                stat.notes.append("description: yt-dlp info.json not available")
                if description_only:
                    raise TranscriptFetchError(
                        f"description_only requested but yt-dlp could not "
                        f"fetch metadata for {url}"
                    )

        return stat
    finally:
        if cleanup_workdir:
            shutil.rmtree(workdir, ignore_errors=True)


# --------------------------------------------------------------------- #
# Internal helpers
# --------------------------------------------------------------------- #


def _yt_dlp_command(yt_dlp_bin: Optional[str]) -> list[str]:
    """Build the base argv for invoking yt-dlp.

    If a binary path is provided, it is used directly. Otherwise we
    invoke ``python -m yt_dlp`` so the per-skill venv's installed
    ``yt-dlp`` package is used regardless of ``$PATH``.
    """
    if yt_dlp_bin:
        return [yt_dlp_bin]
    import sys as _sys

    return [_sys.executable, "-m", "yt_dlp"]


def _classify_failure(stderr: str) -> Optional[str]:
    """Return a short human-readable failure reason from yt-dlp stderr."""
    s = stderr.lower()
    for pat in _HARD_FAILURE_PATTERNS:
        if pat in s:
            return f"hard-failure ({pat})"
    for pat in _RATE_LIMIT_PATTERNS:
        if pat in s:
            return f"rate-limit ({pat})"
    return None


def _stderr_tail(stderr: str, n_lines: int = 5) -> str:
    """Return the last n non-empty *signal* lines of stderr, joined by ' | '.

    yt-dlp leaks a lot of advisory ``WARNING:`` lines (ffmpeg missing,
    impersonation-target absent, …) ahead of the actual ``ERROR:``.
    Including them in the tail bloats ``stat.notes`` and confuses
    downstream parsers, so warnings are filtered out — if the filtered
    result is empty we fall back to the raw tail so a pure-warning
    failure mode is still surfaced.
    """
    if not stderr:
        return ""
    all_lines = [line.strip() for line in stderr.splitlines() if line.strip()]
    signal = [
        ln for ln in all_lines
        if not ln.startswith("WARNING:")
        and "WARNING: " not in ln[:24]
    ]
    chosen = signal if signal else all_lines
    return " | ".join(chosen[-n_lines:])


def _try_download_subtitle(
    *,
    url: str,
    lang: str,
    kind: str,
    workdir: Path,
    pre_existing: set[Path],
    yt_dlp_bin: Optional[str],
    timeout_sec: int,
    cookies_file: Optional[Path] = None,
    with_info_json: bool = False,
) -> tuple[bool, Optional[Path], Optional[str]]:
    """Attempt to download one (kind, lang) subtitle track.

    Returns ``(success, vtt_path, note)``. ``note`` is a human-readable
    string about the attempt (added to TranscriptStat.notes regardless of
    success/failure for transparency, including the cause when yt-dlp
    fails for reasons other than missing-track).
    """
    out_tmpl = str(workdir / "%(id)s.%(ext)s")

    args = [
        *_yt_dlp_command(yt_dlp_bin),
        "--skip-download",
        "--sub-format", "vtt",
        "--sub-langs", lang,
        "--output", out_tmpl,
    ]
    if cookies_file is not None:
        args.extend(["--cookies", str(cookies_file)])
    if with_info_json:
        # Piggy-back the info-json on the subtitle call so a successful
        # ladder step yields both the .vtt and the metadata in one
        # subprocess round-trip — saves a second yt-dlp invocation for
        # the common --with-description case.
        args.append("--write-info-json")
    if kind == "manual":
        args.append("--write-subs")
    elif kind == "auto":
        args.append("--write-auto-subs")
    else:
        return False, None, f"unknown kind={kind!r}"
    # `--` terminates yt-dlp's flag parsing so URLs starting with `-`
    # (a malformed input or a `--cookies-from-browser`-shaped attack
    # string) are treated as a positional, not a flag.
    args.append("--")
    args.append(url)

    try:
        proc = subprocess.run(
            args,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
        )
    except FileNotFoundError as e:
        return False, None, f"yt-dlp not found: {e}"
    except subprocess.TimeoutExpired:
        return False, None, f"timeout fetching {kind}:{lang} (>{timeout_sec}s)"

    failure_reason = _classify_failure(proc.stderr or "")
    if proc.returncode != 0 and failure_reason:
        # Hard or rate-limit failure: don't even bother checking the FS.
        tail = _stderr_tail(proc.stderr or "", 3)
        return False, None, f"{kind}:{lang} {failure_reason}: {tail}" if tail else f"{kind}:{lang} {failure_reason}"

    vtt = _find_new_vtt(workdir, lang, pre_existing)
    if vtt is not None:
        # Add this file to pre_existing so subsequent ladder steps don't
        # accidentally re-claim it.
        pre_existing.add(vtt.resolve())
        return True, vtt, f"got {kind}:{lang} -> {vtt.name}"

    if proc.returncode != 0:
        # Non-zero exit but no recognised failure phrase, and no file.
        tail = _stderr_tail(proc.stderr or "", 3)
        return False, None, (
            f"{kind}:{lang} yt-dlp rc={proc.returncode}: {tail}"
            if tail
            else f"{kind}:{lang} yt-dlp rc={proc.returncode}"
        )
    return False, None, f"no subtitle returned for {kind}:{lang}"


def _find_new_vtt(
    workdir: Path, lang: str, pre_existing: set[Path]
) -> Optional[Path]:
    """Find a freshly-downloaded VTT file matching ``lang`` in workdir.

    yt-dlp names files ``<id>.<lang>.vtt``. We match by suffix to avoid
    needing the video id up front, and exclude any path that was already
    in ``pre_existing`` before the call.
    """
    needle = f".{lang}.vtt"
    candidates = []
    for p in workdir.glob("*.vtt"):
        if p.name.endswith(needle) and p.resolve() not in pre_existing:
            candidates.append(p)
    if not candidates:
        return None
    # Prefer the most recently modified file when multiple match.
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def _pick_fresh_info_json(
    workdir: Path, pre_existing: set[Path]
) -> Optional[dict]:
    """Return the most recent ``*.info.json`` written into ``workdir``.

    Used by :func:`fetch_youtube_transcript` to consume the info-json
    that piggy-backed on the subtitle call. Filters out any file that
    was already present before the call (snapshot semantics).
    """
    candidates = [
        p for p in workdir.glob("*.info.json")
        if p.resolve() not in pre_existing
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    try:
        return json.loads(candidates[0].read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _fetch_video_info(
    *,
    url: str,
    workdir: Path,
    yt_dlp_bin: Optional[str],
    timeout_sec: int,
    cookies_file: Optional[Path],
) -> Optional[dict]:
    """Run yt-dlp ``--write-info-json --skip-download`` and load the JSON.

    Returns the parsed info-json dict, or ``None`` if yt-dlp failed or
    no file was produced. yt-dlp writes the file as
    ``<id>.info.json`` in ``workdir``; we discover it by mtime so
    a pre-existing one from a prior call doesn't get re-claimed.
    """
    pre = {p.resolve() for p in workdir.glob("*.info.json")}
    args = [
        *_yt_dlp_command(yt_dlp_bin),
        "--skip-download",
        "--write-info-json",
        "--no-write-subs",
        "--no-write-auto-subs",
        "--output", str(workdir / "%(id)s.%(ext)s"),
    ]
    if cookies_file is not None:
        args.extend(["--cookies", str(cookies_file)])
    args.append("--")
    args.append(url)
    try:
        proc = subprocess.run(
            args,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_sec,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        # yt-dlp may leave a partial / stale .info.json on failure; do not
        # trust the FS when the process didn't exit cleanly.
        return None
    candidates = [
        p for p in workdir.glob("*.info.json") if p.resolve() not in pre
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    try:
        return json.loads(candidates[0].read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _write_youtube_description(
    *, info: dict, url: str, out_path: Path
) -> Path:
    """Write the ``.description.md`` sidecar from a yt-dlp info-json dict."""
    title = info.get("title") or "(untitled)"
    body = (info.get("description") or "").strip()
    frontmatter: dict = {
        "source": "youtube",
        "url": url,
        "video_id": info.get("id"),
        "title": title,
        "uploader": info.get("uploader") or info.get("channel"),
        "uploader_url": info.get("uploader_url") or info.get("channel_url"),
        "upload_date": _format_upload_date(info.get("upload_date")),
        "duration_sec": _coerce_int(info.get("duration")),
        "view_count": _coerce_int(info.get("view_count")),
        "like_count": _coerce_int(info.get("like_count")),
    }
    return write_description_md(
        out_path, frontmatter=frontmatter, title=title, body=body
    )


def _format_upload_date(raw: object) -> Optional[str]:
    """yt-dlp emits ``upload_date`` as ``YYYYMMDD`` — reshape to ISO."""
    if not isinstance(raw, str) or len(raw) != 8 or not raw.isdigit():
        return None
    return f"{raw[0:4]}-{raw[4:6]}-{raw[6:8]}"


def _coerce_int(value: object) -> Optional[int]:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str) and value.isdigit():
        return int(value)
    return None


# Backwards-compat: a name that was importable before extraction lives
# on for one minor version. Remove when no in-tree callers remain.
__all__ = (
    "DEFAULT_FALLBACK_RU",
    "DEFAULT_TIMEOUT_SEC",
    "TranscriptFetchError",
    "TranscriptStat",
    "extract_video_id",
    "fetch_youtube_transcript",
    "write_stat_sidecar",
    "description_path_for",
)
