"""F4 — 3-tier table detector.

Tier-1: Excel Tables (`<table>` parts in `xl/tables/tableN.xml`).
        Discovered through `ws.tables` (openpyxl exposes them as a
        `TableList` keyed by displayName).
Tier-2: sheet-scope named ranges (`<definedName localSheetId=...>`).
        Workbook-scope names are silently ignored per honest-scope (d).
Tier-3: gap-detection (consecutive empty rows ≥ `gap_rows` AND/OR
        consecutive empty cols ≥ `gap_cols`) over the area not already
        claimed by Tier-1 / Tier-2.

Mode semantics:
- "auto"        : 1 → 2 → 3 fallthrough (default).
- "tables-only" : Tier-1 + Tier-2 only; no gap-detection.
- "whole"       : a single region spanning `ws.dimensions`.

UC-03 A4 (ListObject vs named range overlap): Tier-1 wins — Tier-2
ranges that overlap a Tier-1 region are dropped. Tier-3 is similarly
bounded by previously-claimed bounding boxes.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from openpyxl.utils.cell import range_boundaries

from ._types import TableDetectMode, TableRegion

# ---------------------------------------------------------------------------
# Reserved defined-name filter (TASK 010 §11 patch)
# ---------------------------------------------------------------------------
#
# Source of truth lives in `_reserved_names.json` alongside this module.
# Loaded once when this module is first imported (i.e. on the first
# `xlsx_read.detect_tables` call — `xlsx_read.__init__` does NOT eagerly
# import `_tables`; the JSON read happens lazily at first-use, not at
# package-import).
#
# A defined name that matches any of these patterns is an Excel-internal
# artefact (built-in print area, autofilter range, saved Custom View
# state) and MUST NOT be emitted as a user table by
# `_named_ranges_for_sheet`. Patterns are compiled with `re.IGNORECASE`
# because OOXML §18.2.5 defined names compare case-insensitively in
# Excel — `_XLNM.Print_Area` and `_xlnm.print_area` are the same name.
#
# **Trust boundary:** `_reserved_names.json` is a shipped data file and
# shares the package's trust boundary. Tampering implies a compromised
# installation; the loader does not defend against an attacker who can
# already write into `site-packages`.

_RESERVED_NAMES_PATH = Path(__file__).parent / "_reserved_names.json"

# ReDoS shapes rejected at load time (inlined for parity with
# `xlsx_check_rules.constants.REDOS_REJECT_PATTERNS`; intentionally not
# imported across packages to keep `xlsx_read` self-contained).
_REDOS_REJECT_SHAPES: tuple[re.Pattern[str], ...] = (
    re.compile(r"\(.+\+\)\+"),
    re.compile(r"\(.+\*\)\*"),
    re.compile(r"\(.+\|.+\)\+"),
    re.compile(r"\(.+\|.+\)\*"),
)


def _load_reserved_name_matchers() -> tuple[re.Pattern[str], ...]:
    """Compile reserved-name regexes from `_reserved_names.json`.

    Fails loudly on a missing file, invalid JSON, an invalid regex, a
    pattern matching a known catastrophic-backtracking shape, or a
    missing `regex` key — these are packaging errors, not runtime data,
    and must surface immediately on first-use rather than corrupt the
    filter silently.

    Patterns are compiled with `re.IGNORECASE` because OOXML defined
    names are case-insensitive (see module-level comment).
    """
    with _RESERVED_NAMES_PATH.open("r", encoding="utf-8") as fp:
        spec = json.load(fp)
    out: list[re.Pattern[str]] = []
    for i, entry in enumerate(spec["patterns"]):
        if "regex" not in entry:
            raise KeyError(
                f"{_RESERVED_NAMES_PATH}: patterns[{i}] missing 'regex' key"
            )
        pat = entry["regex"]
        for shape in _REDOS_REJECT_SHAPES:
            if shape.search(pat):
                raise ValueError(
                    f"{_RESERVED_NAMES_PATH}: patterns[{i}] matches ReDoS "
                    f"shape {shape.pattern!r}: {pat!r}"
                )
        out.append(re.compile(pat, re.IGNORECASE))
    return tuple(out)


_RESERVED_NAME_MATCHERS: tuple[re.Pattern[str], ...] = _load_reserved_name_matchers()


# OOXML §18.2.6 caps defined-name length at 255 chars. Anything beyond
# this is either malformed or an attacker probe. Bounding input length
# kills the unbounded-per-name regex-match cost surfaced by
# /vdd-multi-3 security review (HIGH — without this, a workbook with
# 50K names × 100KB each → ~15 GB regex work).
_MAX_DEFINED_NAME_LEN: int = 255

# Zero-width and BOM characters that some workbook tools emit (and that
# attackers use to bypass naive filters). Stripped before matching.
_ZERO_WIDTH_CHARS: str = "​‌‍﻿"


def _is_reserved_name(name: str) -> bool:
    """Return True if `name` is an Excel-reserved defined name.

    Reserved names are auto-generated by Excel (built-in print/filter
    artefacts, Custom-View state) and must be excluded from user-facing
    table detection. See `_reserved_names.json` for the canonical
    pattern list and provenance. Comparison is case-insensitive and
    whitespace-tolerant (strips ASCII whitespace AND zero-width
    characters before matching) to catch malformed or third-party-
    emitter variants.

    **/vdd-multi-3 hardening:**
    - Input length bounded at `_MAX_DEFINED_NAME_LEN` (255 chars per
      OOXML §18.2.6) — names exceeding this are NOT reserved
      (matching skipped entirely, no regex cost on hostile input).
    - Zero-width characters (`U+200B`/`U+200C`/`U+200D`/`U+FEFF`)
      stripped alongside ASCII whitespace — closes the filter-bypass
      vector where attackers prepend ZWSP to a reserved name.

    **Conservative scope on length-cap-then-strip ordering:** the
    length cap fires BEFORE the strip, so a 300-char input with
    ZWSP padding wrapping a 16-char reserved payload is rejected
    (returns False, name surfaces as user-table). This matches OOXML
    §18.2.6 — the spec limit applies to the literal bytes the writer
    emitted, padding included. A 256-byte name is spec-illegal and
    therefore cannot be a built-in reserved name; an attacker who
    pads ZWSP to evade detection is denying themselves the filter,
    not bypassing security. Documented expected behaviour, locked
    by `test_long_input_not_matched_no_redos_surface`.
    """
    if not name:
        return False
    if len(name) > _MAX_DEFINED_NAME_LEN:
        # Spec-illegal length → cannot be a reserved built-in.
        return False
    stripped = name.strip().strip(_ZERO_WIDTH_CHARS)
    if not stripped:
        return False
    return any(m.match(stripped) for m in _RESERVED_NAME_MATCHERS)


def detect_tables(
    wb: Any,
    sheet_name: str,
    *,
    mode: TableDetectMode = "auto",
    gap_rows: int = 2,
    gap_cols: int = 1,
) -> list[TableRegion]:
    """Detect tables on `sheet_name`. See module docstring for tier rules."""
    if mode not in ("auto", "tables-only", "whole"):
        raise ValueError(f"Unknown mode: {mode!r}")
    ws = wb[sheet_name]

    if mode == "whole":
        return [_whole_sheet_region(ws, sheet_name)]

    tier1 = _listobjects_for_sheet(ws, sheet_name)
    tier2 = _named_ranges_for_sheet(wb, sheet_name, claimed=tier1)
    claimed = tier1 + tier2

    if mode == "tables-only":
        return claimed

    tier3 = _gap_detect(ws, sheet_name, claimed, gap_rows, gap_cols)
    return claimed + tier3


# ---------------------------------------------------------------------------
# Tier-1 — Excel Tables (ListObjects)
# ---------------------------------------------------------------------------


def _listobjects_for_sheet(ws: Any, sheet_name: str) -> list[TableRegion]:
    """Emit one region per `<table>` part bound to `ws`.

    openpyxl ≥ 3.1 surfaces tables via `ws.tables` — a `TableList`
    keyed by `displayName`. **Quirk:** `TableList.items()` yields
    `(name, ref_string)` pairs (NOT `(name, Table)`), while
    `TableList[name]` returns the full `Table` object — verified
    empirically against openpyxl 3.1.5. We iterate keys and look up
    each entry to get the `headerRowCount` attribute.
    """
    tables = getattr(ws, "tables", None)
    if not tables:
        return []
    out: list[TableRegion] = []
    for name in list(tables.keys()):
        table = tables[name]
        ref = getattr(table, "ref", None)
        if not ref:
            continue
        left_col, top_row, right_col, bottom_row = range_boundaries(ref)
        hrc = getattr(table, "headerRowCount", 1)
        # openpyxl uses `None` to mean "default = 1"; normalise.
        if hrc is None:
            hrc = 1
        out.append(
            TableRegion(
                sheet=sheet_name,
                top_row=top_row,
                left_col=left_col,
                bottom_row=bottom_row,
                right_col=right_col,
                source="listobject",
                name=name,
                listobject_header_row_count=hrc,
            )
        )
    return out


# ---------------------------------------------------------------------------
# Tier-2 — sheet-scope named ranges
# ---------------------------------------------------------------------------


def _named_ranges_for_sheet(
    wb: Any, sheet_name: str, claimed: list[TableRegion]
) -> list[TableRegion]:
    """Emit one region per sheet-scope `<definedName>` matching `sheet_name`.

    **openpyxl 3.1+ split:** sheet-scope names live on
    `ws.defined_names` (per-sheet `DefinedNameDict`); workbook-scope
    names live on `wb.defined_names`. The library reads ONLY from
    `ws.defined_names` so workbook-scope names are dropped by
    construction (honest-scope D8, no `localSheetId` filtering
    needed). Ranges that overlap a Tier-1 region are dropped
    (UC-03 A4).
    """
    ws = wb[sheet_name]
    out: list[TableRegion] = []
    sheet_defined = getattr(ws, "defined_names", None)
    if not sheet_defined:
        return out
    for name in list(sheet_defined):
        # **TASK 010 §11 patch:** skip Excel-reserved defined names
        # (built-in print areas, autofilter ranges, Custom-View state)
        # so they never surface as user tables. See
        # `_reserved_names.json` for the pattern list.
        if _is_reserved_name(name):
            continue
        dn = sheet_defined[name]
        # **L-M3 fix:** a defined name with multiple comma-separated
        # destinations on the same sheet yields multiple regions; we
        # disambiguate with `#1`, `#2` suffixes so downstream consumers
        # that index by `region.name` don't silently collide.
        dest_count = 0
        local_regions: list[TableRegion] = []
        for dest_sheet, dest_range in dn.destinations:
            if dest_sheet != sheet_name:
                # Destination resolves to a *different* sheet — skip.
                continue
            try:
                left_col, top_row, right_col, bottom_row = range_boundaries(dest_range)
            except (TypeError, ValueError):
                continue
            dest_count += 1
            local_regions.append(TableRegion(
                sheet=sheet_name,
                top_row=top_row,
                left_col=left_col,
                bottom_row=bottom_row,
                right_col=right_col,
                source="named_range",
                name=name,
            ))
        # Single-destination → name stays bare; multi-destination →
        # suffix with `#1`, `#2`, ... in iteration order.
        for i, region in enumerate(local_regions):
            final_name = (
                region.name if dest_count == 1
                else f"{region.name}#{i + 1}"
            )
            disambiguated = TableRegion(
                sheet=region.sheet,
                top_row=region.top_row,
                left_col=region.left_col,
                bottom_row=region.bottom_row,
                right_col=region.right_col,
                source=region.source,
                name=final_name,
            )
            if not _has_overlap(disambiguated, claimed):
                out.append(disambiguated)
    return out


# ---------------------------------------------------------------------------
# Tier-3 — gap-detection
# ---------------------------------------------------------------------------


# Defensive cap on the bounding box we will allocate for gap-detect.
# Malformed `<dimension ref="A1:XFD1048576"/>` would otherwise force
# a multi-GB allocation (M8 sibling concern: pathological openpyxl
# `max_row × max_col` from corrupted-or-malicious workbooks).
#
# **xlsx-8a-06 (R8, 2026-05-13)**: cap raised 1_000_000 → 50_000_000
# (50×) to support legitimate 100K × 20-30 cols ≈ 2-3M cells
# large-table workloads. 50M is 1/343 of the XFD1048576 attack
# envelope (16384 × 1_048_576 ≈ 17.2B cells) — still bounded.
# Bytearray flat-buffer representation (also xlsx-8a-06) keeps
# the worst-case transient memory at 50 MB instead of 400 MB.
# Cap is policy (TASK §7.3 D8 / ARCH §15.10 D-A15); raising
# requires a code-change PR, NOT a CLI flag / env-var override.
_GAP_DETECT_MAX_CELLS: int = 50_000_000


def _gap_detect(
    ws: Any,
    sheet_name: str,
    claimed: list[TableRegion],
    gap_rows: int,
    gap_cols: int,
) -> list[TableRegion]:
    """Split the un-claimed area on ≥ gap_rows empty rows / ≥ gap_cols empty cols.

    Single-pass implementation backed by openpyxl's row-stream
    iterator (`iter_rows`), so the cost scales with **actually
    populated cells**, not with `ws.max_row × ws.max_column`. The
    streaming form is also safe in `read_only=True` mode (the
    historical nested `ws.cell(r, c)` pattern is fatal there —
    each call re-walks the sheet XML).

    1. Bounds: `ws.calculate_dimension()` parsed via openpyxl's
       `range_boundaries`. Refuses inputs with > `_GAP_DETECT_MAX_CELLS`
       cells in the dimension bbox (defense against malformed
       `<dimension>` payloads).
    2. Stream rows via `iter_rows(values_only=True)`. Build the
       occupancy matrix incrementally, masking out cells inside
       any `claimed` region as they pass.
    3. Find row-bands → col-bands → tight bbox per region.
    """
    top, left, bottom, right = _resolve_dim_bbox(ws)
    if top is None:
        return []
    n_rows = bottom - top + 1
    n_cols = right - left + 1
    if n_rows * n_cols > _GAP_DETECT_MAX_CELLS:
        # The bbox is implausibly large for a real spreadsheet — refuse
        # rather than allocate a multi-GB grid. The caller can override
        # by passing `mode="whole"` (one region, no occupancy work) or
        # `mode="tables-only"` (no gap-detect at all).
        raise ValueError(
            f"_gap_detect: dimension bbox {n_rows}×{n_cols}={n_rows * n_cols} "
            f"exceeds {_GAP_DETECT_MAX_CELLS} cells; switch to "
            f"mode='tables-only' or mode='whole' on this sheet"
        )

    # xlsx-8a-06 (R8, D-A16): `_build_claimed_mask` may return `None`
    # when `claimed` is empty (common case for `--tables auto` on a
    # sheet with no Tier-1 / Tier-2 regions). Consumer below guards
    # with `if claimed_mask is not None and claimed_mask[...]`.
    claimed_mask = _build_claimed_mask(top, left, bottom, right, claimed)

    # **xlsx-8a-06 (R8, D-A16)**: occupancy is a flat `bytearray` of
    # length `n_rows * n_cols`, indexed `[r * n_cols + c]`. 8× memory
    # reduction vs the v1 `list[list[bool]]` representation (1 byte
    # vs 8 bytes/ref on 64-bit Python). Big-O unchanged. The buffer
    # is zero-initialised by `bytearray(N)`, so we only set bits to
    # 1 for occupied cells — no per-row padding step needed.
    occupancy = bytearray(n_rows * n_cols)
    for r_idx, row in enumerate(
        ws.iter_rows(
            min_row=top, max_row=bottom,
            min_col=left, max_col=right,
            values_only=True,
        )
    ):
        # Guard against `iter_rows` over-shooting in the unlikely
        # case where openpyxl returns more rows than n_rows.
        if r_idx >= n_rows:
            break
        for c_idx, v in enumerate(row):
            if c_idx >= n_cols:
                break
            if (
                claimed_mask is not None
                and claimed_mask[r_idx * n_cols + c_idx]
            ):
                continue  # leave occupancy[r,c] at 0 (claimed)
            if v is not None and v != "":
                occupancy[r_idx * n_cols + c_idx] = 1

    # Step 2: find row-bands. Aggregate each row to a bool via `any`
    # over its column-slice in the flat buffer.
    row_aggregate = [
        any(occupancy[r * n_cols + c] for c in range(n_cols))
        for r in range(n_rows)
    ]
    row_bands = _split_on_gap(row_aggregate, gap_rows, base_index=top)
    if not row_bands:
        return []

    out: list[TableRegion] = []
    counter = 1
    for r_start, r_end in row_bands:
        # Step 3: find col-bands in this row-band — collapse the band
        # vertically: a column is occupied iff *any* row in the band
        # uses it. Iterate directly over the flat buffer slice.
        band_top_idx = r_start - top
        band_bot_idx = r_end - top  # inclusive
        col_occupancy = [
            any(
                occupancy[r * n_cols + c]
                for r in range(band_top_idx, band_bot_idx + 1)
            )
            for c in range(n_cols)
        ]
        col_bands = _split_on_gap(col_occupancy, gap_cols, base_index=left)
        for c_start, c_end in col_bands:
            # Trim each col-band to the actual tight bbox within the
            # row-band so leading/trailing empty edges don't bloat the
            # region.
            tight = _tight_bbox(
                occupancy,
                band_top_idx, band_bot_idx,
                c_start - left, c_end - left,
                n_cols=n_cols,
            )
            if tight is None:
                continue
            tr, tc, br, bc = tight
            out.append(
                TableRegion(
                    sheet=sheet_name,
                    top_row=top + tr,
                    left_col=left + tc,
                    bottom_row=top + br,
                    right_col=left + bc,
                    source="gap_detect",
                    name=f"Table-{counter}",
                )
            )
            counter += 1
    return out


def _resolve_dim_bbox(ws: Any) -> tuple[int, int, int, int] | tuple[None, None, None, None]:
    """Return the (top, left, bottom, right) inclusive bbox of `ws.dimensions`.

    Falls back to (max_row, max_column) when the dimension parse fails.
    Returns four `None`s for a genuinely empty sheet.
    """
    dims = getattr(ws, "dimensions", None) or ""
    if dims:
        try:
            left, top, right, bottom = range_boundaries(dims)
            return top, left, bottom, right
        except (TypeError, ValueError):
            pass
    if ws.max_row and ws.max_column:
        return 1, 1, ws.max_row, ws.max_column
    return None, None, None, None  # type: ignore[return-value]


def _build_claimed_mask(
    top: int, left: int, bottom: int, right: int, claimed: list[TableRegion]
) -> bytearray | None:
    """Build a flat `bytearray` claimed-cell mask.

    **xlsx-8a-06 (R8, D-A16)**: returns ``None`` when ``claimed`` is
    empty (Tier-1 + Tier-2 produced no regions — common for sheets
    with only gap-detect-able data). Caller in ``_gap_detect`` MUST
    guard with ``if claimed_mask is not None and claimed_mask[...]``
    before indexing — see the consumer pattern there.

    For the non-empty case, the mask is a flat ``bytearray(h * w)``
    indexed ``[r * w + c]``; 8× memory reduction over the v1
    ``list[list[bool]]`` form. Big-O unchanged at O(h × w) for
    allocation + O(sum of region areas) for population.
    """
    if not claimed:
        return None
    h, w = bottom - top + 1, right - left + 1
    mask = bytearray(h * w)
    for region in claimed:
        for r in range(region.top_row, region.bottom_row + 1):
            for c in range(region.left_col, region.right_col + 1):
                if top <= r <= bottom and left <= c <= right:
                    mask[(r - top) * w + (c - left)] = 1
    return mask


def _split_on_gap(
    occupied: list[bool], gap: int, base_index: int = 1
) -> list[tuple[int, int]]:
    """Find runs of occupied indices, splitting on `gap`-or-more empties.

    Returns list of (start, end) inclusive in the **absolute** index
    space defined by `base_index` (so e.g. row 1-based or col 1-based
    can be returned without renumbering at the call site).

    A gap of *exactly* `gap` empties splits — e.g. `gap=2` splits on
    `[True, False, False, True]` (2 empties = split) but NOT on
    `[True, False, True]` (1 empty < 2 = same band).
    """
    out: list[tuple[int, int]] = []
    run_start: int | None = None
    empty_run = 0
    for i, occ in enumerate(occupied):
        if occ:
            if run_start is None:
                run_start = i
            empty_run = 0
        else:
            if run_start is not None:
                empty_run += 1
                if empty_run >= gap:
                    out.append((base_index + run_start, base_index + i - empty_run))
                    run_start = None
                    empty_run = 0
    if run_start is not None:
        out.append((base_index + run_start, base_index + len(occupied) - 1 - empty_run))
    return out


def _tight_bbox(
    occupancy: bytearray,
    r_lo: int,
    r_hi: int,
    c_lo: int,
    c_hi: int,
    *,
    n_cols: int,
) -> tuple[int, int, int, int] | None:
    """Return the tightest occupied bbox inside the band, or None if empty.

    Returned tuple is `(top, left, bottom, right)` in 0-based grid
    coordinates relative to the occupancy matrix.

    **xlsx-8a-06 (R8, D-A16)**: `occupancy` is a flat `bytearray`
    indexed `[r * n_cols + c]`. The `n_cols` parameter is keyword-
    only and required (caller must thread it through).
    """
    tr, tc, br, bc = None, None, None, None
    for r in range(r_lo, r_hi + 1):
        for c in range(c_lo, c_hi + 1):
            if occupancy[r * n_cols + c]:
                if tr is None or r < tr:
                    tr = r
                if br is None or r > br:
                    br = r
                if tc is None or c < tc:
                    tc = c
                if bc is None or c > bc:
                    bc = c
    if tr is None:
        return None
    return tr, tc, br, bc  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Overlap helper
# ---------------------------------------------------------------------------


def _has_overlap(region: TableRegion, claimed: list[TableRegion]) -> bool:
    for c in claimed:
        if (
            region.top_row <= c.bottom_row
            and c.top_row <= region.bottom_row
            and region.left_col <= c.right_col
            and c.left_col <= region.right_col
        ):
            return True
    return False


def _whole_sheet_region(ws: Any, sheet_name: str) -> TableRegion:
    """Whole-sheet region trimmed to the actual non-empty content bbox.

    **TASK 010 §11 patch v2:** `ws.max_row` / `ws.max_column` come from
    the `<dimension>` ref in the sheet XML, which Excel routinely
    inflates beyond the real data range (legacy formatting on empty
    rows, deleted rows that left phantom dimension entries, etc.). A
    "whole sheet" emit that respects `ws.max_row` blindly therefore
    produces hundreds-to-thousands of trailing empty CSV lines on
    real-world reports. The fix scans the dimension bbox via
    `iter_rows(values_only=True)` and contracts to the tight
    `(last_row, last_col)` of any non-empty cell.

    **vdd-multi-2 HIGH fix:** the previous "cap → bail with un-trimmed
    bbox" path produced exactly the catastrophic 1M-row CSV output
    the trim was designed to prevent. The cap is now enforced as an
    **in-loop iteration counter** that breaks scan early and emits the
    best-effort trimmed bbox we've seen so far. Output is always
    bounded by `_GAP_DETECT_MAX_CELLS` cells regardless of input
    dimension; no garbage-region fallback. Empty sheet → degenerate
    1×1 region (so downstream emit code doesn't choke on
    bottom_row < top_row).
    """
    # **vdd-multi-3 MED-Logic-2 fix:** `ws.max_row` / `ws.max_column`
    # can be `None` in `read_only=True` streaming mode when the
    # `<dimension>` ref is absent or unparseable. `max(None, 1)`
    # raises `TypeError`; coalesce to 0 first.
    dim_max_row = max(ws.max_row or 0, 1)
    dim_max_col = max(ws.max_column or 0, 1)

    cells_scanned = 0
    last_row = 0
    last_col = 0
    for r_idx, row in enumerate(
        ws.iter_rows(
            min_row=1, max_row=dim_max_row,
            min_col=1, max_col=dim_max_col,
            values_only=True,
        ),
        start=1,
    ):
        for c_idx, v in enumerate(row, start=1):
            cells_scanned += 1
            if cells_scanned > _GAP_DETECT_MAX_CELLS:
                # **vdd-multi-3 HIGH (3-critic convergence) fix:**
                # emit a soft warning so downstream callers (and the
                # shim's `_emit_warnings_to_stderr`) can surface the
                # truncation. Without this the region silently shrinks
                # to whatever the scan reached, which on hostile input
                # (sparse data at row ≥ 1M with inflated `<dimension>`)
                # produces silent data loss. Sibling `_gap_detect`
                # raises on the same condition; here we degrade
                # gracefully because `mode="whole"` is the default and
                # raising would break legitimate large-but-valid
                # workbooks. Soft warning is the documented middle path.
                import warnings as _warnings
                _warnings.warn(
                    f"_whole_sheet_region: cell-scan cap "
                    f"({_GAP_DETECT_MAX_CELLS} cells) fired before "
                    f"reaching dim bbox end; data beyond "
                    f"row {last_row}/col {last_col} dropped. "
                    f"Switch to --tables auto for explicit handling.",
                    UserWarning,
                    stacklevel=2,
                )
                # In-loop cap fires: emit the best-effort trimmed
                # bbox seen so far (NEVER the inflated dim bbox; that
                # would produce 1M-row CSV garbage on hostile input).
                if last_row == 0:
                    return TableRegion(
                        sheet=sheet_name,
                        top_row=1, left_col=1,
                        bottom_row=1, right_col=1,
                        source="gap_detect", name="Table-1",
                    )
                return TableRegion(
                    sheet=sheet_name,
                    top_row=1, left_col=1,
                    bottom_row=last_row, right_col=last_col,
                    source="gap_detect", name="Table-1",
                )
            if v is not None and v != "":
                if r_idx > last_row:
                    last_row = r_idx
                if c_idx > last_col:
                    last_col = c_idx

    if last_row == 0:
        return TableRegion(
            sheet=sheet_name,
            top_row=1, left_col=1,
            bottom_row=1, right_col=1,
            source="gap_detect", name="Table-1",
        )

    return TableRegion(
        sheet=sheet_name,
        top_row=1, left_col=1,
        bottom_row=last_row, right_col=last_col,
        source="gap_detect", name="Table-1",
    )


# ---------------------------------------------------------------------------
# xlsx-8a-09 (R11) — Smart header detection (type-pattern-based)
# ---------------------------------------------------------------------------
#
# Caller-side opt-in via `header_rows='smart'`. The library scans the
# top of the region for a row that "looks like" a header (high
# string-ratio, broad column coverage) followed by data rows with
# stable types per column. If such a row sits below the region's
# `top_row` (i.e. there's a metadata block above the data table),
# returns the offset; otherwise returns 0.
#
# **Score-only**: the heuristic competes purely on the
# `string_ratio + 1.5×coverage + 2×stability + 0.5×depth` score
# vs the `_SMART_SHIFT_THRESHOLD` floor. No special-case deferral
# for merged-banner fixtures (iter-2 fix, 2026-05-13): on
# `multi_row_header.xlsx`-style workbooks (`A1:C1` "2026 plan"
# merged banner over `Q1`/`Q2`/`Q3` sub-headers), smart shifts to
# the sub-header row and produces leaf-like keys. Callers needing
# the merge-concatenated multi-level form (`"2026 plan › Q1"`)
# must use `--header-rows auto`/`leaf` — `smart` is the
# "find-the-data-table" recipe and is non-overlapping with
# `auto`/`leaf` only at the OUTPUT shape level, not at the
# scoring-input level.
#
# Algorithm constants (tunable; not part of public API).

_SMART_PROBE_ROWS: int = 20          # candidate header rows to consider
_SMART_STABILITY_DEPTH: int = 5      # rows after candidate to score
_SMART_MIN_STRING_RATIO: float = 0.5 # candidate row must be ≥50% strings
_SMART_SHIFT_THRESHOLD: float = 3.5  # min score to justify a shift


def _normalize_type_for_smart(v: Any) -> str:
    """Return a coarse type tag for type-stability scoring."""
    import datetime as _dt
    if v is None or v == "":
        return "empty"
    if isinstance(v, bool):
        return "bool"
    if isinstance(v, (int, float)):
        return "number"
    if isinstance(v, (_dt.datetime, _dt.date)):
        return "date"
    if isinstance(v, _dt.time):
        return "time"
    if isinstance(v, str):
        return "str"
    return type(v).__name__


def _detect_data_table_offset(ws: Any, region: TableRegion) -> int:
    """Return the row offset within `region` where the data table starts.

    Returns 0 if the region already starts at the data table (or if
    we cannot confidently identify a metadata block). Returns N > 0
    if a metadata block of N rows sits above a clearly-identifiable
    header + data run.

    xlsx-8a-09 (R11; iter-3 2026-05-13): used when caller passes
    `header_rows='smart'`. **Score-only** — does NOT defer to
    merge-based detection; competes purely on the
    `string_ratio + 1.5×coverage + 2×stability + 0.5×depth` score
    (max 5.0) vs the `_SMART_SHIFT_THRESHOLD` floor. Callers
    needing the merge-concatenated multi-level form must use
    `header_rows='auto'` or `'leaf'` instead.

    Algorithm: for each candidate row in the first `_SMART_PROBE_ROWS`
    of the region, score by `string_ratio + 1.5×coverage + 2×stability
    + 0.5×depth`. Pick the highest-scoring row (tie-break: earliest).
    If best score ≥ `_SMART_SHIFT_THRESHOLD` AND best offset > 0,
    return that offset; otherwise 0.
    """
    n_cols = region.right_col - region.left_col + 1
    n_rows = region.bottom_row - region.top_row + 1
    if n_rows < 2 or n_cols < 1:
        return 0

    # **xlsx-8a-09 iter-2 (2026-05-13)**: previous version unconditionally
    # deferred to merge-based detection when any column-spanning merge
    # anchored in the top of the region. That was over-conservative —
    # in workbooks like `masterdata_report_202604.xlsx::Timesheet`, the
    # row-1 merge is a **banner** (a long title spanning cols 1-7),
    # NOT a multi-row-header band; the real column headers sit on
    # row 7 and the heuristic SHOULD find them.
    #
    # The defer guard is removed. The heuristic now always runs and
    # competes purely on score. Multi-row-header fixtures with merged
    # banners (e.g. `multi_row_header.xlsx` with A1:C1 "2026 plan"
    # over Q1/Q2/Q3 sub-headers) will produce a non-zero shift under
    # `--header-rows smart` (matches the `leaf` mode's intent), which
    # is the right semantics for the "find the data table" mode.
    # `--header-rows auto`/`leaf` continue to use merge-based
    # detection unchanged.

    # Cache the first PROBE + STABILITY_DEPTH rows once via iter_rows
    # (single XML walk; works in read_only mode too).
    probe_limit = min(_SMART_PROBE_ROWS + _SMART_STABILITY_DEPTH, n_rows)
    cached_rows: list[list[Any]] = []
    for r_offset, row in enumerate(ws.iter_rows(
        min_row=region.top_row,
        max_row=region.top_row + probe_limit - 1,
        min_col=region.left_col,
        max_col=region.right_col,
        values_only=True,
    )):
        cached_rows.append(list(row))
        if r_offset + 1 >= probe_limit:
            break
    if len(cached_rows) < 2:
        return 0

    # **xlsx-8a-09 iter-2 fix (2026-05-13)**: `min_non_empty_cols`
    # is now computed against the **effective data width** (the
    # max column index where data rows below the candidate have
    # any non-empty cell), NOT the region width `n_cols`.
    #
    # Why: a narrow data table (e.g. 7 cols) inside a region whose
    # width is inflated by sparse meta-banner cells (e.g. a
    # "Period: ..." line that lights up col 7 of a 25-col `<dimension>`)
    # would otherwise have its real header rejected because
    # 7 cells < n_cols // 2 = 12. The masterdata Timesheet fixture
    # exhibits this exact pattern. Per-candidate `data_width` is
    # computed from rows below by taking the max non-empty col
    # index, capped at `n_cols`.
    #
    # The absolute floor of 3 stays: a "header" with < 3 cells is
    # almost certainly not a real header — even narrow tables have
    # at least date / value / description.
    candidates: list[tuple[int, float]] = []

    for r_offset in range(min(_SMART_PROBE_ROWS, len(cached_rows) - 1)):
        row_values = cached_rows[r_offset]
        non_empty = [v for v in row_values if v not in (None, "")]

        sample_below = cached_rows[r_offset + 1: r_offset + 1 + _SMART_STABILITY_DEPTH]
        # **iter-3 fix (vdd-multi M1)**: require at least 2 rows
        # below to score stability meaningfully. With only 1 sample,
        # `stability_ratio` is trivially 1.0 (any single value has 1
        # type), which can push borderline candidates over the
        # threshold for the WRONG row (e.g. r_offset near the end
        # of `cached_rows`). The R8+ realistic data tables have far
        # more than 2 rows below the header, so this floor is safe.
        if len(sample_below) < 2:
            continue

        # Compute the effective data width from rows BELOW the candidate.
        data_width = 0
        for r in sample_below:
            for c_idx in range(len(r) - 1, -1, -1):
                if r[c_idx] not in (None, ""):
                    if c_idx + 1 > data_width:
                        data_width = c_idx + 1
                    break
        if data_width == 0:
            # No data below → not a header. Skip.
            continue
        min_non_empty_cols = max(3, data_width // 2)

        if len(non_empty) < min_non_empty_cols:
            continue
        string_count = sum(1 for v in non_empty if isinstance(v, str))
        string_ratio = string_count / len(non_empty)
        if string_ratio < _SMART_MIN_STRING_RATIO:
            continue

        stable_cols = 0
        populated_cols = 0
        # **Iter-2**: only consider columns within `data_width` for the
        # stability check (cells beyond the actual data table can never
        # be "stable" — they're empty in the sample).
        for c_idx in range(min(len(row_values), data_width)):
            h_val = row_values[c_idx]
            if h_val in (None, ""):
                continue
            col_vals = [
                r[c_idx] if c_idx < len(r) else None
                for r in sample_below
            ]
            col_non_empty = [v for v in col_vals if v not in (None, "")]
            if not col_non_empty:
                continue
            populated_cols += 1
            col_types = {_normalize_type_for_smart(v) for v in col_non_empty}
            if len(col_types) == 1:
                stable_cols += 1
        if populated_cols == 0:
            continue
        stability_ratio = stable_cols / populated_cols

        # **iter-3 fix (vdd-multi H1)**: clamp `coverage_ratio` at
        # 1.0. Without the clamp, a candidate row that is broader
        # than the data table below (wide banner over a narrow
        # data table — e.g. 20 strings on row 1 above a 7-col
        # data section) produces `coverage_ratio = 20/7 ≈ 2.86`,
        # blowing the documented theoretical max score of 5.0 and
        # making the threshold trivially passable on hostile or
        # ill-formed input. The clamp preserves the "wider header
        # is better" signal up to data_width, then saturates.
        coverage_ratio = min(1.0, len(non_empty) / data_width)
        n_rows_with_data = sum(
            1 for r in sample_below
            if any(v not in (None, "") for v in r)
        )
        depth_score = min(1.0, n_rows_with_data / _SMART_STABILITY_DEPTH)

        score = (
            string_ratio * 1.0
            + coverage_ratio * 1.5
            + stability_ratio * 2.0
            + depth_score * 0.5
        )
        candidates.append((r_offset, score))

    if not candidates:
        return 0
    candidates.sort(key=lambda x: (-x[1], x[0]))
    best_offset, best_score = candidates[0]
    if best_score < _SMART_SHIFT_THRESHOLD or best_offset == 0:
        return 0
    return best_offset
